// skier built-in task factories (exports only)
export { copyAssetsTask, CopyAssetsConfig } from './copyAssetsTask';
export { processCssTask, ProcessCssConfig } from './processCssTask';
export { generateSitemapTask, GenerateSitemapConfig } from './generateSitemapTask';
export { generateHtmlTask, GenerateHtmlConfig } from './generateHtmlTask';
export { generateItemisedTask, GenerateItemisedConfig } from './generateItemisedTask';
export { cleanAndCreateOutputTask, CleanAndCreateOutputConfig } from './cleanAndCreateOutputTask';
export { generateRssFeedTask, GenerateRssFeedConfig } from './generateRssFeedTask';
export { generateChangelogTask, GenerateChangelogConfig } from './generateChangelogTask';
export { readMarkdownTask, ReadMarkdownConfig } from './readMarkdownTask';
export { setGlobalsTask, SetGlobalsConfig } from './setGlobalsTask';
